[profile.default]
src = "contracts"
out = "contracts/out"
libs = ["node_modules", "contracts/lib"]
solc_version = "0.8.20"
optimizer_runs = 200
allow_paths = ["contracts/lib/openzeppelin-contracts"]
exclude = ["contracts/lib/openzeppelin-contracts/test", "contracts/lib/openzeppelin-contracts/certora"]

[profile.default.fmt]
line_length = 100
bracket_spacing = true

[rpc_endpoints]
xlayer = "https://rpc.xlayer.tech"

[etherscan]
xlayer = { key = "${ETHERSCAN_API_KEY}", chain = 196 }
